### ISSUE TITLE
Normalizing RNA Expressions

### ISSUE THREAD

**Issue by FMGS666** [theislab/CFGen#9]
Hello it's Lorenzo

I was wondering, as we discussed last time with Ale, about the way the [`RNASeqLoader`](https://github.com/theislab/CFGen/blob/main/cfgen/data/scrnaseq_loader.py) handles the count normalization.

In the "Model details" section of the CFGen paper's Appendix it's written "Notice that scRNA-seq data are provided by the encoder in their log-transformed version for training stability. Intuitively, the loss is evaluated on the original counts."  However, in the [`__getitem__`](https://github.com/theislab/CFGen/blob/35350cff92f2ac463a311fa09694e582380b4cc6/cfgen/data/scrnaseq_loader.py#L115-L121) method the loader only normalizes the data when the following condition is satisfied `if mod == "atac" and (not self.is_binarized)`, which means that the only modality to be preprocessed is ATAC, and RNA expressions remain unaltered. 

Is this a wanted behavior?

**Comment by MLubetzki** [comment]
Hey Lorenzo :) Good catch, this is indeed unwanted behavior. We wanted to fix this a while ago, but it seems to have gotten lost. I will fix this later!

**Comment by MLubetzki** [comment]
Fixed with commit fa710f6
